#include "buffer.c"
#include "bufferCombined.c"
#include "bufferVision.c"
#include "control.c"
#include "encoder.c"
#include "gps.c"
//#include "img-test.c"
#include "joystick.c"
//#include "landmarks.c"
//#include "laplace.c"
#include "location.c"
#include "macros.c"
#include "main.c"
//#include "main_notsure.c"
#include "nmeap01.c"
#include "objects.c"
//#include "os5000.c"
#include "roboteq.c"
#include "serial.c"
#include "sick.c"
#include "socket.c"

#include "vision_nav.c"
#include "visualizer.c"

ODOMETRY encoderVar;
double cpmLeft, cpmRight;
